### ISSUE TITLE
Add i18n Translation

### ISSUE THREAD

**Issue by SerQuicky** [SerQuicky/ostratum-translation-manager#27]
Support the English and German language

**Comment by afink70** [comment]
Hi, if you tell me how to translate, maybe I could help :)

**Comment by SerQuicky** [comment]
Thanks, I will soon add the i18 translation package and the corresponding English key-pair values. Afterward, I will assign the ticket to you and you can create a PQ for this.

**Comment by SerQuicky** [comment]
Do you speak any languages besides English and German? @afkin70
